// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrguy9GCY9yz6rF_2KicVzzpa--9mYws',
    appId: '1:568554500246:web:ac783de45fa19ca97152b7',
    messagingSenderId: '568554500246',
    projectId: 'farmerapp-7eb53',
    authDomain: 'farmerapp-7eb53.firebaseapp.com',
    storageBucket: 'farmerapp-7eb53.appspot.com',
    measurementId: 'G-ZSV00HK6TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIQ1rvtdZz_v9bkTWxh9VVPtBD_fEYw4',
    appId: '1:568554500246:android:b1ae4a296c3adb297152b7',
    messagingSenderId: '568554500246',
    projectId: 'farmerapp-7eb53',
    storageBucket: 'farmerapp-7eb53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuFb2m_jskNlGoT09ipXQTIAWEVSrdnq4',
    appId: '1:568554500246:ios:4a5412a084a5ba5f7152b7',
    messagingSenderId: '568554500246',
    projectId: 'farmerapp-7eb53',
    storageBucket: 'farmerapp-7eb53.appspot.com',
    iosClientId: '568554500246-kteo05ff8pnkqgbkhi6m39a7icu5cnsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.krushi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuFb2m_jskNlGoT09ipXQTIAWEVSrdnq4',
    appId: '1:568554500246:ios:6a01375f792888097152b7',
    messagingSenderId: '568554500246',
    projectId: 'farmerapp-7eb53',
    storageBucket: 'farmerapp-7eb53.appspot.com',
    iosClientId: '568554500246-ojjbb2fi67kmqifl7fb1tghlar99nsnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.krushi.RunnerTests',
  );
}
